# Generated by Django 5.1.2 on 2024-11-07 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0003_icon'),
    ]

    operations = [
        migrations.AddField(
            model_name='icon',
            name='title',
            field=models.CharField(default='Sin título', max_length=50),
        ),
    ]
