# Generated by Django 5.1.2 on 2024-11-07 16:50

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0004_icon_title'),
    ]

    operations = [
        migrations.CreateModel(
            name='Education',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='portfolio/images/')),
                ('title', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=150)),
                ('date_ini', models.DateField(blank=True, default=datetime.date.today, null=True)),
                ('date_fin', models.DateField(blank=True, default=datetime.date.today, null=True)),
            ],
        ),
    ]
